### ISSUE TITLE
asm.tree.analysis.AnalyzerException with Joda-Time-2.0

### ISSUE THREAD

**Issue by kevinjalbert** [david-schuler/javalanche#13]
I've encountered a new error (similar to #5 as the transformation seems to be causing the problem). I achieve the following error when I try to perform mutation testing on [joda-time-2.0](http://sourceforge.net/projects/joda-time/files/joda-time/2.0/) (with all the mutation operators enabled):

```
 [exec]     [junit] org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 36: Expected an object reference, but found .
 ...
 [exec]     [junit] Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Expected an object reference, but found .
 ...
 [exec]     [junit] java.lang.RuntimeException: Error at instruction 36: Expected an object reference, but found . parse(Ljava/lang/String;I)I
```

It seems to be occurring from the following location in joda-time (according to the stack-trace):

```
 [exec]     [junit]     at org.joda.time.format.PeriodFormatterBuilder.appendSuffix(PeriodFormatterBuilder.java:576)
 [exec]     [junit]     at org.joda.time.format.PeriodFormat.wordBased(PeriodFormat.java:101)
 [exec]     [junit]     at org.joda.time.format.TestPeriodFormat.test_wordBased_fr_formatStandard(TestPeriodFormat.java:112)
```

I've also included the full log of the [Error as a Gist](https://gist.github.com/2036944). This error keeps restarting a mutation task (effectively never allowing the mutation testing process to finish).

**Comment by kevinjalbert** [comment]
I'm closing this issue as a great deal of time has passed. If there is renewed interest just reopen or make a new issue and link to this one.
